package generator

import (
	"reflect"
	"strings"
	"testing"

	"github.com/dklinux7/devkit/internal/config"
	"github.com/dklinux7/devkit/internal/fs"
)

func TestGenerate_MarkdownTargets(t *testing.T) {
	m := fs.NewMemFS()
	ws := &config.Workspace{Name: "Test", ActiveContext: "work"}

	content := "<!-- Generated by devkit -->\n\nHello world.\n"
	r, err := Generate(m, "/project", content, ws, "/templates")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	wantWritten := len(MarkdownTargets) + len(MDCTargets)
	if len(r.Written) != wantWritten {
		t.Fatalf("wrote %d files, want %d", len(r.Written), wantWritten)
	}

	for _, name := range MarkdownTargets {
		data, err := m.ReadFile("/project/" + name)
		if err != nil {
			t.Fatalf("missing %s: %v", name, err)
		}
		if string(data) != content {
			t.Fatalf("%s content mismatch", name)
		}
	}
}

func TestGenerate_OverwriteReporting(t *testing.T) {
	m := fs.NewMemFS()
	if err := m.WriteFile("/project/CLAUDE.md", []byte("old content"), 0644); err != nil {
		t.Fatal(err)
	}
	ws := &config.Workspace{Name: "Test", ActiveContext: "work"}

	content := "new content"
	r, err := Generate(m, "/project", content, ws, "/templates")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	if len(r.Overwritten) == 0 {
		t.Fatal("expected overwrite to be reported")
	}
	found := false
	for _, name := range r.Overwritten {
		if name == "CLAUDE.md" {
			found = true
		}
	}
	if !found {
		t.Fatal("CLAUDE.md should be in overwritten list")
	}
}

func TestGenerate_StructuredTargets(t *testing.T) {
	m := fs.NewMemFS()
	if err := m.WriteFile("/templates/opencode.json.tmpl", []byte("{\"context\": \"{{.Workspace.Name}}\"}\n"), 0644); err != nil {
		t.Fatal(err)
	}
	ws := &config.Workspace{Name: "Dev", ActiveContext: "work"}

	r, err := Generate(m, "/project", "composed content", ws, "/templates")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	foundOpencode := false
	for _, name := range r.Written {
		if name == "opencode.json" {
			foundOpencode = true
		}
	}
	if !foundOpencode {
		t.Fatal("opencode.json should be written when template exists")
	}

	data, err := m.ReadFile("/project/opencode.json")
	if err != nil {
		t.Fatalf("missing opencode.json: %v", err)
	}
	if string(data) != "{\"context\": \"Dev\"}\n" {
		t.Fatalf("opencode.json content = %q", string(data))
	}
}

func TestGenerate_SkipsStructuredWithoutTemplate(t *testing.T) {
	m := fs.NewMemFS()
	ws := &config.Workspace{Name: "Test", ActiveContext: "work"}

	r, err := Generate(m, "/project", "content", ws, "/templates")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	for _, name := range r.Written {
		if name == "opencode.json" || name == ".claude/settings.json" {
			t.Fatalf("should not write %s without template", name)
		}
	}
}

func TestGenerate_CreatesSubdirectory(t *testing.T) {
	m := fs.NewMemFS()
	if err := m.WriteFile("/templates/.claude/settings.json.tmpl", []byte(`{"name": "{{.Workspace.Name}}"}`), 0644); err != nil {
		t.Fatal(err)
	}
	ws := &config.Workspace{Name: "Test", ActiveContext: "work"}

	_, err := Generate(m, "/project", "content", ws, "/templates")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	if !m.Exists("/project/.claude/settings.json") {
		t.Fatal("expected .claude/settings.json to be created")
	}
}

func TestGenerate_MDCTarget(t *testing.T) {
	m := fs.NewMemFS()
	ws := &config.Workspace{Name: "Test", ActiveContext: "work"}

	content := "<!-- Generated by devkit -->\n\nHello world.\n"
	_, err := Generate(m, "/project", content, ws, "/templates")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	mdcPath := "/project/.cursor/rules/devkit-context.mdc"
	if !m.Exists(mdcPath) {
		t.Fatalf("expected %s to be written", mdcPath)
	}

	data, err := m.ReadFile(mdcPath)
	if err != nil {
		t.Fatalf("reading mdc file: %v", err)
	}

	if !strings.Contains(string(data), "alwaysApply: true") {
		t.Fatalf("mdc file missing alwaysApply frontmatter, got: %s", string(data))
	}
	if !strings.Contains(string(data), content) {
		t.Fatalf("mdc file missing content, got: %s", string(data))
	}
}

func TestGenerateNoSliceMutation(t *testing.T) {
	original := make([]string, len(MarkdownTargets))
	copy(original, MarkdownTargets)

	fsys := fs.NewMemFS()
	if err := fsys.MkdirAll("/target", 0755); err != nil {
		t.Fatal(err)
	}

	ws := &config.Workspace{
		Name:          "test",
		ActiveContext: "work",
		ExtraTargets:  []string{"extra1.md", "extra2.md"},
	}

	if _, err := Generate(fsys, "/target", "test content", ws, "/templates"); err != nil {
		t.Fatal(err)
	}

	if !reflect.DeepEqual(MarkdownTargets, original) {
		t.Errorf("Generate mutated MarkdownTargets: got %v, want %v", MarkdownTargets, original)
	}
}

func TestGenerateRejectsPathTraversal(t *testing.T) {
	fsys := fs.NewMemFS()
	if err := fsys.MkdirAll("/target", 0755); err != nil {
		t.Fatal(err)
	}

	ws := &config.Workspace{
		Name:          "test",
		ActiveContext: "work",
		ExtraTargets:  []string{"../../etc/passwd"},
	}

	_, err := Generate(fsys, "/target", "content", ws, "/templates")
	if err == nil {
		t.Fatal("expected error for path traversal in extra_targets, got nil")
	}
	if !strings.Contains(err.Error(), "escapes") {
		t.Errorf("expected 'escapes' in error, got: %v", err)
	}
}

func TestGenerate_ExtraTargets(t *testing.T) {
	m := fs.NewMemFS()
	ws := &config.Workspace{
		Name:          "Test",
		ActiveContext: "work",
		ExtraTargets:  []string{"custom/tool.md", ".amp/context.md"},
	}

	content := "<!-- Generated by devkit -->\n\nHello world.\n"
	r, err := Generate(m, "/project", content, ws, "/templates")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	for _, extra := range ws.ExtraTargets {
		path := "/project/" + extra
		if !m.Exists(path) {
			t.Fatalf("expected extra target %s to be written", path)
		}
		data, err := m.ReadFile(path)
		if err != nil {
			t.Fatalf("reading %s: %v", extra, err)
		}
		if string(data) != content {
			t.Fatalf("%s content mismatch", extra)
		}
	}

	foundCustom := false
	for _, name := range r.Written {
		if name == "custom/tool.md" {
			foundCustom = true
		}
	}
	if !foundCustom {
		t.Fatal("custom/tool.md should be in written list")
	}
}
