package generator

import (
	"testing"

	"github.com/dklinux7/devkit/internal/config"
	"github.com/dklinux7/devkit/internal/fs"
)

func TestGenerate_MarkdownTargets(t *testing.T) {
	m := fs.NewMemFS()
	ws := &config.Workspace{Name: "Test", ActiveContext: "work"}

	content := "<!-- Generated by devkit -->\n\nHello world.\n"
	r, err := Generate(m, "/project", content, ws, "/templates")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	if len(r.Written) != len(MarkdownTargets) {
		t.Fatalf("wrote %d files, want %d", len(r.Written), len(MarkdownTargets))
	}

	for _, name := range MarkdownTargets {
		data, err := m.ReadFile("/project/" + name)
		if err != nil {
			t.Fatalf("missing %s: %v", name, err)
		}
		if string(data) != content {
			t.Fatalf("%s content mismatch", name)
		}
	}
}

func TestGenerate_OverwriteReporting(t *testing.T) {
	m := fs.NewMemFS()
	m.WriteFile("/project/CLAUDE.md", []byte("old content"), 0644)
	ws := &config.Workspace{Name: "Test", ActiveContext: "work"}

	content := "new content"
	r, err := Generate(m, "/project", content, ws, "/templates")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	if len(r.Overwritten) == 0 {
		t.Fatal("expected overwrite to be reported")
	}
	found := false
	for _, name := range r.Overwritten {
		if name == "CLAUDE.md" {
			found = true
		}
	}
	if !found {
		t.Fatal("CLAUDE.md should be in overwritten list")
	}
}

func TestGenerate_StructuredTargets(t *testing.T) {
	m := fs.NewMemFS()
	m.WriteFile("/templates/opencode.toml.tmpl", []byte("[context]\ncontent = \"{{.Workspace.Name}}\"\n"), 0644)
	ws := &config.Workspace{Name: "Dev", ActiveContext: "work"}

	r, err := Generate(m, "/project", "composed content", ws, "/templates")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	foundOpencode := false
	for _, name := range r.Written {
		if name == "opencode.toml" {
			foundOpencode = true
		}
	}
	if !foundOpencode {
		t.Fatal("opencode.toml should be written when template exists")
	}

	data, err := m.ReadFile("/project/opencode.toml")
	if err != nil {
		t.Fatalf("missing opencode.toml: %v", err)
	}
	if string(data) != "[context]\ncontent = \"Dev\"\n" {
		t.Fatalf("opencode.toml content = %q", string(data))
	}
}

func TestGenerate_SkipsStructuredWithoutTemplate(t *testing.T) {
	m := fs.NewMemFS()
	ws := &config.Workspace{Name: "Test", ActiveContext: "work"}

	r, err := Generate(m, "/project", "content", ws, "/templates")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	for _, name := range r.Written {
		if name == "opencode.toml" || name == ".claude/settings.json" {
			t.Fatalf("should not write %s without template", name)
		}
	}
}

func TestGenerate_CreatesSubdirectory(t *testing.T) {
	m := fs.NewMemFS()
	m.WriteFile("/templates/.claude/settings.json.tmpl", []byte(`{"name": "{{.Workspace.Name}}"}`), 0644)
	ws := &config.Workspace{Name: "Test", ActiveContext: "work"}

	_, err := Generate(m, "/project", "content", ws, "/templates")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	if !m.Exists("/project/.claude/settings.json") {
		t.Fatal("expected .claude/settings.json to be created")
	}
}
