package composer

import (
	"fmt"
	"strings"

	"github.com/dklinux7/devkit/internal/devctx"
)

const (
	Header   = "<!-- Generated by devkit. Do not edit. Contains private context. Source: ~/.devkit/ -->"
	WarnSize = 16 * 1024
	FailSize = 32 * 1024
)

type Result struct {
	Content  string
	Size     int
	Warnings []string
}

func Compose(sources *devctx.Sources, force bool) (*Result, error) {
	var sections []string

	for _, id := range sources.Identity {
		if s := strings.TrimSpace(string(id)); s != "" {
			sections = append(sections, s)
		}
	}

	if s := strings.TrimSpace(string(sources.Context)); s != "" {
		sections = append(sections, s)
	}

	if s := strings.TrimSpace(string(sources.Donts)); s != "" {
		sections = append(sections, s)
	}

	for _, lesson := range sources.Lessons {
		if s := strings.TrimSpace(string(lesson)); s != "" {
			sections = append(sections, s)
		}
	}

	body := strings.Join(sections, "\n\n")
	content := Header + "\n\n" + body + "\n"

	r := &Result{
		Content: content,
		Size:    len(content),
	}

	if r.Size > FailSize && !force {
		return nil, fmt.Errorf("output is %dKB (limit: 32KB) — use --force to override", r.Size/1024)
	}
	if r.Size > WarnSize {
		r.Warnings = append(r.Warnings, fmt.Sprintf("output is %dKB (recommended limit: 16KB)", r.Size/1024))
	}

	return r, nil
}
